language: python
python:
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- pypy
- pypy3
install:
- pip install -r requirements.txt
- pip install coverage coveralls
script:
- coverage run --source=fantasy_sport -m unittest test.TestFantasySportLeague
- coverage run --source=fantasy_sport -m unittest test.TestFantasySportPlayer
- coverage run --source=fantasy_sport -m unittest test.TestFantasySportTeam
- coverage run --source=fantasy_sport -m unittest test.TestFantasySportRoster
- coverage run --source=fantasy_sport -m unittest test.TestFantasySportTransaction
after_success:
- coverage report
- coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_aa858aa3cffd_key -iv $encrypted_aa858aa3cffd_iv
  -in oauth.json.enc -out oauth.json -d
